// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [
      TSubRelationship in Extract<
        TRelationship["fields"][number],
        prismic.CustomTypeModelFetchContentRelationshipLevel1
      > as TSubRelationship["id"]
    ]: ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
  } & // Group
  {
    [
      TGroup in Extract<
        TRelationship["fields"][number],
        | prismic.CustomTypeModelFetchGroupLevel1
        | prismic.CustomTypeModelFetchGroupLevel2
      > as TGroup["id"]
    ]: TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [
      TFieldKey in Extract<TRelationship["fields"][number], string>
    ]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [
    ID in Exclude<TCustomType[number], string>["id"]
  ]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Layout → Involve CTA*
 */
export interface LayoutDocumentDataInvolveCtaItem {
  /**
   * CTA field in *Layout → Involve CTA*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.involve_cta[].cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Text field in *Layout → Involve CTA*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.involve_cta[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;
}

/**
 * Item in *Layout → Seva*
 */
export interface LayoutDocumentDataModalSevaItem {
  /**
   * Seva ID field in *Layout → Seva*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_seva[].seva_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  seva_id: prismic.KeyTextField;

  /**
   * Title field in *Layout → Seva*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_seva[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *Layout → Seva*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_seva[].subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;
}

/**
 * Item in *Layout → Amounts*
 */
export interface LayoutDocumentDataModalAmountsItem {
  /**
   * Amount field in *Layout → Amounts*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_amounts[].amount
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  amount: prismic.NumberField;
}

/**
 * Content for Layout documents
 */
interface LayoutDocumentData {
  /**
   * Logo field in *Layout*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Trust Name field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.trust_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  trust_name: prismic.KeyTextField;

  /**
   * Trust Name2 field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.trust_name2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  trust_name2: prismic.KeyTextField; /**
   * Link field in *Layout*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.link
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * CTA field in *Layout*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.cta
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary" | "Tertiary"
    >
  >; /**
   * Featured Image field in *Layout*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.featured_image
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Involve Title field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.involve_title
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  involve_title: prismic.KeyTextField;

  /**
   * Description field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.description
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Involve CTA field in *Layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.involve_cta[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  involve_cta: prismic.GroupField<Simplify<LayoutDocumentDataInvolveCtaItem>>;

  /**
   * Copyright Text field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.copyright_text
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  copyright_text: prismic.KeyTextField; /**
   * Title field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_title
   * - **Tab**: Modal
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  modal_title: prismic.KeyTextField;

  /**
   * Subtitle field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_subtitle
   * - **Tab**: Modal
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  modal_subtitle: prismic.KeyTextField;

  /**
   * Description field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_description
   * - **Tab**: Modal
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  modal_description: prismic.KeyTextField;

  /**
   * Seva field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_seva_title
   * - **Tab**: Modal
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  modal_seva_title: prismic.KeyTextField;

  /**
   * Seva field in *Layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_seva[]
   * - **Tab**: Modal
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  modal_seva: prismic.GroupField<Simplify<LayoutDocumentDataModalSevaItem>>;

  /**
   * Donation Amount Title field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_donation_amount_title
   * - **Tab**: Modal
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  modal_donation_amount_title: prismic.KeyTextField;

  /**
   * Amounts field in *Layout*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_amounts[]
   * - **Tab**: Modal
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  modal_amounts: prismic.GroupField<
    Simplify<LayoutDocumentDataModalAmountsItem>
  >;

  /**
   * Enter Amount Label field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_enter_amount_label
   * - **Tab**: Modal
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  modal_enter_amount_label: prismic.KeyTextField;

  /**
   * Donor Information Title field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_donor_information_title
   * - **Tab**: Modal
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  modal_donor_information_title: prismic.KeyTextField;

  /**
   * Full Name Label field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_full_name_label
   * - **Tab**: Modal
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  modal_full_name_label: prismic.KeyTextField;

  /**
   * Email Address Label field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_email_label
   * - **Tab**: Modal
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  modal_email_label: prismic.KeyTextField;

  /**
   * Phone Number Label field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_phone_label
   * - **Tab**: Modal
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  modal_phone_label: prismic.KeyTextField;

  /**
   * PAN Number Label field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_pan_label
   * - **Tab**: Modal
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  modal_pan_label: prismic.KeyTextField;

  /**
   * Info Title field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_info_title
   * - **Tab**: Modal
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  modal_info_title: prismic.KeyTextField;

  /**
   * Info field in *Layout*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_info
   * - **Tab**: Modal
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  modal_info: prismic.RichTextField;

  /**
   * Highlight Text field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_highlight_text
   * - **Tab**: Modal
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  modal_highlight_text: prismic.KeyTextField;

  /**
   * Submit Text field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_submit_text
   * - **Tab**: Modal
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  modal_submit_text: prismic.KeyTextField;

  /**
   * Submitting Text field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_submitting_text
   * - **Tab**: Modal
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  modal_submitting_text: prismic.KeyTextField;

  /**
   * Success Title field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_success_title
   * - **Tab**: Modal
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  modal_success_title: prismic.KeyTextField;

  /**
   * Success Description field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_success_description
   * - **Tab**: Modal
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  modal_success_description: prismic.KeyTextField;

  /**
   * Done Label field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_done_label
   * - **Tab**: Modal
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  modal_done_label: prismic.KeyTextField;

  /**
   * Close Label field in *Layout*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: layout.modal_close_label
   * - **Tab**: Modal
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  modal_close_label: prismic.KeyTextField;
}

/**
 * Layout document from Prismic
 *
 * - **API ID**: `layout`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LayoutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LayoutDocumentData>,
    "layout",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | HeroSlice
  | FeaturedProfileSlice
  | InitiativeFeatureSlice
  | FeatureGridSlice
  | ImpactOverviewSlice
  | FoundationOverviewSlice
  | VisionMissionSlice
  | ContactInquirySlice
  | PillarFeatureSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;

  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Social sharing title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.og_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  og_title: prismic.KeyTextField;

  /**
   * Social sharing description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.og_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  og_description: prismic.KeyTextField;

  /**
   * Social sharing image (1200 x 630) field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.og_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  og_image: prismic.ImageField<never>;

  /**
   * Hide this page from search engines field in *Page*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **API ID Path**: page.noindex
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  noindex: prismic.BooleanField;

  /**
   * Page schema type field in *Page*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: page.schema_type
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  schema_type: prismic.SelectField<
    "WebPage" | "AboutPage" | "ContactPage" | "CollectionPage"
  >;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = LayoutDocument | PageDocument;

/**
 * Item in *Contact Inquiry → Default → Primary → Contact Details*
 */
export interface ContactInquirySliceDefaultPrimaryContactDetailsItem {
  /**
   * Icon field in *Contact Inquiry → Default → Primary → Contact Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.contact_details[].icon
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon: prismic.KeyTextField;

  /**
   * Title field in *Contact Inquiry → Default → Primary → Contact Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.contact_details[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Contact Inquiry → Default → Primary → Contact Details*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.contact_details[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Contact Inquiry → Default → Primary*
 */
export interface ContactInquirySliceDefaultPrimary {
  /**
   * Anchor ID field in *Contact Inquiry → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.anchor_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  anchor_id: prismic.KeyTextField;

  /**
   * Office Title field in *Contact Inquiry → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.office_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  office_title: prismic.KeyTextField;

  /**
   * Contact Details field in *Contact Inquiry → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.contact_details[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  contact_details: prismic.GroupField<
    Simplify<ContactInquirySliceDefaultPrimaryContactDetailsItem>
  >;

  /**
   * Form Title field in *Contact Inquiry → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.form_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  form_title: prismic.KeyTextField;

  /**
   * Form Description field in *Contact Inquiry → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.form_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  form_description: prismic.KeyTextField;

  /**
   * Name Label field in *Contact Inquiry → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.name_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name_label: prismic.KeyTextField;

  /**
   * Gender Label field in *Contact Inquiry → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.gender_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  gender_label: prismic.KeyTextField;

  /**
   * Email Label field in *Contact Inquiry → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.email_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email_label: prismic.KeyTextField;

  /**
   * Phone Number Label field in *Contact Inquiry → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.phone_number_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phone_number_label: prismic.KeyTextField;

  /**
   * Message Label field in *Contact Inquiry → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.message_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  message_label: prismic.KeyTextField;

  /**
   * Submit Label field in *Contact Inquiry → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.submit_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  submit_label: prismic.KeyTextField;
}

/**
 * Default variation for Contact Inquiry Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactInquirySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactInquirySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact Inquiry*
 */
type ContactInquirySliceVariation = ContactInquirySliceDefault;

/**
 * Contact Inquiry Shared Slice
 *
 * - **API ID**: `contact_inquiry`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactInquirySlice = prismic.SharedSlice<
  "contact_inquiry",
  ContactInquirySliceVariation
>;

/**
 * Item in *Feature Grid → Default → Primary → Cards*
 */
export interface FeatureGridSliceDefaultPrimaryCardsItem {
  /**
   * Card title field in *Feature Grid → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Card description field in *Feature Grid → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Key Description field in *Feature Grid → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.cards[].key_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  key_description: prismic.RichTextField;
}

/**
 * Primary content in *Feature Grid → Default → Primary*
 */
export interface FeatureGridSliceDefaultPrimary {
  /**
   * Anchor ID field in *Feature Grid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.anchor_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  anchor_id: prismic.KeyTextField;

  /**
   * Pre-title field in *Feature Grid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.pretitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  pretitle: prismic.KeyTextField;

  /**
   * Title field in *Feature Grid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Introduction field in *Feature Grid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.introduction
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  introduction: prismic.RichTextField;

  /**
   * Key Title field in *Feature Grid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.key_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  key_title: prismic.KeyTextField;

  /**
   * Cards field in *Feature Grid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<FeatureGridSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for Feature Grid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Feature Grid*
 */
type FeatureGridSliceVariation = FeatureGridSliceDefault;

/**
 * Feature Grid Shared Slice
 *
 * - **API ID**: `feature_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureGridSlice = prismic.SharedSlice<
  "feature_grid",
  FeatureGridSliceVariation
>;

/**
 * Primary content in *Featured Profile → Default → Primary*
 */
export interface FeaturedProfileSliceDefaultPrimary {
  /**
   * Anchor ID field in *Featured Profile → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_profile.default.primary.anchor_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  anchor_id: prismic.KeyTextField;

  /**
   * overlay pretitle field in *Featured Profile → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_profile.default.primary.overlay_pretitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  overlay_pretitle: prismic.KeyTextField;

  /**
   * overlay title field in *Featured Profile → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_profile.default.primary.overlay_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  overlay_title: prismic.KeyTextField;

  /**
   * overlay description field in *Featured Profile → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_profile.default.primary.overlay_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  overlay_description: prismic.KeyTextField;

  /**
   * Featured image field in *Featured Profile → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_profile.default.primary.featured_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Overlay details field in *Featured Profile → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_profile.default.primary.overlay_details
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  overlay_details: prismic.RichTextField;

  /**
   * Content field in *Featured Profile → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_profile.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Callout title field in *Featured Profile → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_profile.default.primary.callout_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  callout_title: prismic.KeyTextField;

  /**
   * Callout content field in *Featured Profile → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_profile.default.primary.callout_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  callout_content: prismic.RichTextField;

  /**
   * Quote field in *Featured Profile → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_profile.default.primary.quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;
}

/**
 * Default variation for Featured Profile Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedProfileSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedProfileSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Featured Profile*
 */
type FeaturedProfileSliceVariation = FeaturedProfileSliceDefault;

/**
 * Featured Profile Shared Slice
 *
 * - **API ID**: `featured_profile`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedProfileSlice = prismic.SharedSlice<
  "featured_profile",
  FeaturedProfileSliceVariation
>;

/**
 * Item in *Foundation Overview → Default → Primary → Repetable Item*
 */
export interface FoundationOverviewSliceDefaultPrimaryRepetableItemItem {
  /**
   * Title field in *Foundation Overview → Default → Primary → Repetable Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foundation_overview.default.primary.repetable_item[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *Foundation Overview → Default → Primary*
 */
export interface FoundationOverviewSliceDefaultPrimary {
  /**
   * Anchor ID field in *Foundation Overview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foundation_overview.default.primary.anchor_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  anchor_id: prismic.KeyTextField;

  /**
   * Featured Image field in *Foundation Overview → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: foundation_overview.default.primary.featured_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Title Description field in *Foundation Overview → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foundation_overview.default.primary.title_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title_description: prismic.RichTextField;

  /**
   * Description field in *Foundation Overview → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foundation_overview.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Repetable Item field in *Foundation Overview → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: foundation_overview.default.primary.repetable_item[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  repetable_item: prismic.GroupField<
    Simplify<FoundationOverviewSliceDefaultPrimaryRepetableItemItem>
  >;

  /**
   * Trust highlights field in *Foundation Overview → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foundation_overview.default.primary.highlights
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  highlights: prismic.RichTextField;
}

/**
 * Default variation for Foundation Overview Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FoundationOverviewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FoundationOverviewSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Foundation Overview*
 */
type FoundationOverviewSliceVariation = FoundationOverviewSliceDefault;

/**
 * Foundation Overview Shared Slice
 *
 * - **API ID**: `foundation_overview`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FoundationOverviewSlice = prismic.SharedSlice<
  "foundation_overview",
  FoundationOverviewSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Anchor ID field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.anchor_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  anchor_id: prismic.KeyTextField;

  /**
   * Background Color field in *Hero → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background_color: prismic.SelectField<"Light" | "Dark">;

  /**
   * Background Type field in *Hero → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.default.primary.background_type
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  background_type: prismic.BooleanField;

  /**
   * Pre Title Background Color field in *Hero → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.pre_title_background_color
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  pre_title_background_color: prismic.SelectField<"Light" | "Dark">;

  /**
   * Pre-title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.pre_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  pre_title: prismic.KeyTextField;

  /**
   * Content field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * CTA field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Solid Orange" | "Solid Blue" | "Solid White" | "Solid Cream"
    >
  >;

  /**
   * CTA Size field in *Hero → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.default.primary.cta_size
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  cta_size: prismic.BooleanField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Impact Overview → Default → Primary → Repetable Item*
 */
export interface ImpactOverviewSliceDefaultPrimaryRepetableItemItem {
  /**
   * Impact Statement field in *Impact Overview → Default → Primary → Repetable Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impact_overview.default.primary.repetable_item[].impact_statement
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  impact_statement: prismic.KeyTextField;
}

/**
 * Primary content in *Impact Overview → Default → Primary*
 */
export interface ImpactOverviewSliceDefaultPrimary {
  /**
   * Anchor ID field in *Impact Overview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impact_overview.default.primary.anchor_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  anchor_id: prismic.KeyTextField;

  /**
   * title field in *Impact Overview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impact_overview.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Impact Overview → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impact_overview.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Highlight Text field in *Impact Overview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impact_overview.default.primary.highlight_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  highlight_text: prismic.KeyTextField;

  /**
   * Repetable Item field in *Impact Overview → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: impact_overview.default.primary.repetable_item[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  repetable_item: prismic.GroupField<
    Simplify<ImpactOverviewSliceDefaultPrimaryRepetableItemItem>
  >;
}

/**
 * Default variation for Impact Overview Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImpactOverviewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImpactOverviewSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Impact Overview*
 */
type ImpactOverviewSliceVariation = ImpactOverviewSliceDefault;

/**
 * Impact Overview Shared Slice
 *
 * - **API ID**: `impact_overview`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImpactOverviewSlice = prismic.SharedSlice<
  "impact_overview",
  ImpactOverviewSliceVariation
>;

/**
 * Item in *Initiative Feature → Default → Primary → Initiatives*
 */
export interface InitiativeFeatureSliceDefaultPrimaryInitiativesItem {
  /**
   * Initiative description field in *Initiative Feature → Default → Primary → Initiatives*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: initiative_feature.default.primary.initiatives[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *Initiative Feature → Default → Primary*
 */
export interface InitiativeFeatureSliceDefaultPrimary {
  /**
   * Anchor ID field in *Initiative Feature → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: initiative_feature.default.primary.anchor_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  anchor_id: prismic.KeyTextField;

  /**
   * Description field in *Initiative Feature → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: initiative_feature.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Initiatives field in *Initiative Feature → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: initiative_feature.default.primary.initiatives[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  initiatives: prismic.GroupField<
    Simplify<InitiativeFeatureSliceDefaultPrimaryInitiativesItem>
  >;

  /**
   * Highlight Text field in *Initiative Feature → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: initiative_feature.default.primary.highlight_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  highlight_text: prismic.KeyTextField;
}

/**
 * Default variation for Initiative Feature Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InitiativeFeatureSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InitiativeFeatureSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Initiative Feature*
 */
type InitiativeFeatureSliceVariation = InitiativeFeatureSliceDefault;

/**
 * Initiative Feature Shared Slice
 *
 * - **API ID**: `initiative_feature`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InitiativeFeatureSlice = prismic.SharedSlice<
  "initiative_feature",
  InitiativeFeatureSliceVariation
>;

/**
 * Item in *Pillar Feature → Default → Primary → Statistics*
 */
export interface PillarFeatureSliceDefaultPrimaryStatisticsItem {
  /**
   * Value field in *Pillar Feature → Default → Primary → Statistics*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pillar_feature.default.primary.statistics[].value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value: prismic.KeyTextField;

  /**
   * Label field in *Pillar Feature → Default → Primary → Statistics*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pillar_feature.default.primary.statistics[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;
}

/**
 * Item in *Pillar Feature → Default → Primary → Donation options*
 */
export interface PillarFeatureSliceDefaultPrimaryDonationsItem {
  /**
   * Donation label field in *Pillar Feature → Default → Primary → Donation options*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pillar_feature.default.primary.donations[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Amount (INR) field in *Pillar Feature → Default → Primary → Donation options*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: pillar_feature.default.primary.donations[].amount
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  amount: prismic.NumberField;
}

/**
 * Primary content in *Pillar Feature → Default → Primary*
 */
export interface PillarFeatureSliceDefaultPrimary {
  /**
   * Anchor ID field in *Pillar Feature → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pillar_feature.default.primary.anchor_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  anchor_id: prismic.KeyTextField;

  /**
   * Pillar name field in *Pillar Feature → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pillar_feature.default.primary.pillar_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  pillar_name: prismic.KeyTextField;

  /**
   * Title field in *Pillar Feature → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pillar_feature.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Introduction field in *Pillar Feature → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pillar_feature.default.primary.introduction
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  introduction: prismic.RichTextField;

  /**
   * Featured image field in *Pillar Feature → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pillar_feature.default.primary.featured_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Additional featured image field in *Pillar Feature → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pillar_feature.default.primary.additional_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  additional_image: prismic.ImageField<never>;

  /**
   * Image caption field in *Pillar Feature → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pillar_feature.default.primary.image_caption
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image_caption: prismic.KeyTextField;

  /**
   * Initiatives label field in *Pillar Feature → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pillar_feature.default.primary.initiatives_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  initiatives_title: prismic.KeyTextField;

  /**
   * Initiatives field in *Pillar Feature → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pillar_feature.default.primary.initiatives
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  initiatives: prismic.RichTextField;

  /**
   * Project title field in *Pillar Feature → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pillar_feature.default.primary.project_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  project_title: prismic.RichTextField;

  /**
   * Project details field in *Pillar Feature → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pillar_feature.default.primary.project_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  project_content: prismic.RichTextField;

  /**
   * Statistics field in *Pillar Feature → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: pillar_feature.default.primary.statistics[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  statistics: prismic.GroupField<
    Simplify<PillarFeatureSliceDefaultPrimaryStatisticsItem>
  >;

  /**
   * Donation panel title field in *Pillar Feature → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pillar_feature.default.primary.donations_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  donations_title: prismic.KeyTextField;

  /**
   * Donation options field in *Pillar Feature → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: pillar_feature.default.primary.donations[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  donations: prismic.GroupField<
    Simplify<PillarFeatureSliceDefaultPrimaryDonationsItem>
  >;

  /**
   * Call to action field in *Pillar Feature → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: pillar_feature.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Image on right field in *Pillar Feature → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **API ID Path**: pillar_feature.default.primary.image_on_right
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  image_on_right: prismic.BooleanField;
}

/**
 * Default variation for Pillar Feature Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PillarFeatureSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PillarFeatureSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Pillar Feature*
 */
type PillarFeatureSliceVariation = PillarFeatureSliceDefault;

/**
 * Pillar Feature Shared Slice
 *
 * - **API ID**: `pillar_feature`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PillarFeatureSlice = prismic.SharedSlice<
  "pillar_feature",
  PillarFeatureSliceVariation
>;

/**
 * Item in *Vision Mission → Default → Primary → Pillars*
 */
export interface VisionMissionSliceDefaultPrimaryPillarsItem {
  /**
   * Pillar title field in *Vision Mission → Default → Primary → Pillars*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_mission.default.primary.pillars[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Pillar description field in *Vision Mission → Default → Primary → Pillars*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_mission.default.primary.pillars[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *Vision Mission → Default → Primary*
 */
export interface VisionMissionSliceDefaultPrimary {
  /**
   * Anchor ID field in *Vision Mission → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_mission.default.primary.anchor_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  anchor_id: prismic.KeyTextField;

  /**
   * Vision Pretitle field in *Vision Mission → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_mission.default.primary.vision_pretitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  vision_pretitle: prismic.KeyTextField;

  /**
   * Vision Title field in *Vision Mission → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_mission.default.primary.vision_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  vision_title: prismic.KeyTextField;

  /**
   * Vision Quote field in *Vision Mission → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_mission.default.primary.vision_quote
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  vision_quote: prismic.KeyTextField;

  /**
   * Vision Footer field in *Vision Mission → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_mission.default.primary.vision_footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  vision_footer: prismic.KeyTextField;

  /**
   * Mission Pretitle field in *Vision Mission → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_mission.default.primary.mission_pretitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  mission_pretitle: prismic.KeyTextField;

  /**
   * Mission Title field in *Vision Mission → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_mission.default.primary.mission_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  mission_title: prismic.KeyTextField;

  /**
   * Mission Description field in *Vision Mission → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_mission.default.primary.mission_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  mission_description: prismic.KeyTextField;

  /**
   * Pillars field in *Vision Mission → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_mission.default.primary.pillars[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  pillars: prismic.GroupField<
    Simplify<VisionMissionSliceDefaultPrimaryPillarsItem>
  >;
}

/**
 * Default variation for Vision Mission Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VisionMissionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VisionMissionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Vision Mission*
 */
type VisionMissionSliceVariation = VisionMissionSliceDefault;

/**
 * Vision Mission Shared Slice
 *
 * - **API ID**: `vision_mission`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VisionMissionSlice = prismic.SharedSlice<
  "vision_mission",
  VisionMissionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      LayoutDocument,
      LayoutDocumentData,
      LayoutDocumentDataInvolveCtaItem,
      LayoutDocumentDataModalSevaItem,
      LayoutDocumentDataModalAmountsItem,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContactInquirySlice,
      ContactInquirySliceDefaultPrimaryContactDetailsItem,
      ContactInquirySliceDefaultPrimary,
      ContactInquirySliceVariation,
      ContactInquirySliceDefault,
      FeatureGridSlice,
      FeatureGridSliceDefaultPrimaryCardsItem,
      FeatureGridSliceDefaultPrimary,
      FeatureGridSliceVariation,
      FeatureGridSliceDefault,
      FeaturedProfileSlice,
      FeaturedProfileSliceDefaultPrimary,
      FeaturedProfileSliceVariation,
      FeaturedProfileSliceDefault,
      FoundationOverviewSlice,
      FoundationOverviewSliceDefaultPrimaryRepetableItemItem,
      FoundationOverviewSliceDefaultPrimary,
      FoundationOverviewSliceVariation,
      FoundationOverviewSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ImpactOverviewSlice,
      ImpactOverviewSliceDefaultPrimaryRepetableItemItem,
      ImpactOverviewSliceDefaultPrimary,
      ImpactOverviewSliceVariation,
      ImpactOverviewSliceDefault,
      InitiativeFeatureSlice,
      InitiativeFeatureSliceDefaultPrimaryInitiativesItem,
      InitiativeFeatureSliceDefaultPrimary,
      InitiativeFeatureSliceVariation,
      InitiativeFeatureSliceDefault,
      PillarFeatureSlice,
      PillarFeatureSliceDefaultPrimaryStatisticsItem,
      PillarFeatureSliceDefaultPrimaryDonationsItem,
      PillarFeatureSliceDefaultPrimary,
      PillarFeatureSliceVariation,
      PillarFeatureSliceDefault,
      VisionMissionSlice,
      VisionMissionSliceDefaultPrimaryPillarsItem,
      VisionMissionSliceDefaultPrimary,
      VisionMissionSliceVariation,
      VisionMissionSliceDefault,
    };
  }
}
