// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [
      TSubRelationship in Extract<
        TRelationship["fields"][number],
        prismic.CustomTypeModelFetchContentRelationshipLevel1
      > as TSubRelationship["id"]
    ]: ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
  } & // Group
  {
    [
      TGroup in Extract<
        TRelationship["fields"][number],
        | prismic.CustomTypeModelFetchGroupLevel1
        | prismic.CustomTypeModelFetchGroupLevel2
      > as TGroup["id"]
    ]: TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [
      TFieldKey in Extract<TRelationship["fields"][number], string>
    ]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [
    ID in Exclude<TCustomType[number], string>["id"]
  ]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type PageDocumentDataSlicesSlice =
  | TextSectionSlice
  | HeroSlice
  | ValuesActionsSlice
  | ImpactStatsSlice
  | FeaturedProfileSlice
  | InitiativeFeatureSlice
  | FeatureGridSlice
  | CtaBannerSlice
  | ProgramDirectorySlice
  | PartnershipCalloutSlice
  | ImpactOverviewSlice
  | FoundationOverviewSlice
  | VisionMissionSlice
  | ContactInquirySlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;

  /**
   * Title field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Item in *Contact Inquiry → Default → Primary → Contact Details*
 */
export interface ContactInquirySliceDefaultPrimaryContactDetailsItem {
  /**
   * Icon field in *Contact Inquiry → Default → Primary → Contact Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.contact_details[].icon
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon: prismic.KeyTextField;

  /**
   * Title field in *Contact Inquiry → Default → Primary → Contact Details*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.contact_details[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Contact Inquiry → Default → Primary → Contact Details*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.contact_details[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Contact Inquiry → Default → Primary*
 */
export interface ContactInquirySliceDefaultPrimary {
  /**
   * Office Title field in *Contact Inquiry → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.office_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  office_title: prismic.KeyTextField;

  /**
   * Contact Details field in *Contact Inquiry → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.contact_details[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  contact_details: prismic.GroupField<
    Simplify<ContactInquirySliceDefaultPrimaryContactDetailsItem>
  >;

  /**
   * Form Title field in *Contact Inquiry → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.form_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  form_title: prismic.KeyTextField;

  /**
   * Form Description field in *Contact Inquiry → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.form_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  form_description: prismic.KeyTextField;

  /**
   * Name Label field in *Contact Inquiry → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.name_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name_label: prismic.KeyTextField;

  /**
   * Gender Label field in *Contact Inquiry → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.gender_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  gender_label: prismic.KeyTextField;

  /**
   * Email Label field in *Contact Inquiry → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.email_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email_label: prismic.KeyTextField;

  /**
   * Phone Number Label field in *Contact Inquiry → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.phone_number_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  phone_number_label: prismic.KeyTextField;

  /**
   * Message Label field in *Contact Inquiry → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.message_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  message_label: prismic.KeyTextField;

  /**
   * Submit Label field in *Contact Inquiry → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_inquiry.default.primary.submit_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  submit_label: prismic.KeyTextField;
}

/**
 * Default variation for Contact Inquiry Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactInquirySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactInquirySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact Inquiry*
 */
type ContactInquirySliceVariation = ContactInquirySliceDefault;

/**
 * Contact Inquiry Shared Slice
 *
 * - **API ID**: `contact_inquiry`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactInquirySlice = prismic.SharedSlice<
  "contact_inquiry",
  ContactInquirySliceVariation
>;

/**
 * Primary content in *Call to Action Banner → Default → Primary*
 */
export interface CtaBannerSliceDefaultPrimary {
  /**
   * Pre-title field in *Call to Action Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_banner.default.primary.pretitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  pretitle: prismic.KeyTextField;

  /**
   * Content field in *Call to Action Banner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_banner.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Actions field in *Call to Action Banner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_banner.default.primary.actions
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  actions: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "explore" | "support"
    >
  >;
}

/**
 * Default variation for Call to Action Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Call to Action Banner*
 */
type CtaBannerSliceVariation = CtaBannerSliceDefault;

/**
 * Call to Action Banner Shared Slice
 *
 * - **API ID**: `cta_banner`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaBannerSlice = prismic.SharedSlice<
  "cta_banner",
  CtaBannerSliceVariation
>;

/**
 * Item in *Feature Grid → Default → Primary → Cards*
 */
export interface FeatureGridSliceDefaultPrimaryCardsItem {
  /**
   * Card title field in *Feature Grid → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.cards[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Card description field in *Feature Grid → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.cards[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Key Description field in *Feature Grid → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.cards[].key_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  key_description: prismic.RichTextField;
}

/**
 * Primary content in *Feature Grid → Default → Primary*
 */
export interface FeatureGridSliceDefaultPrimary {
  /**
   * Pre-title field in *Feature Grid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.pretitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  pretitle: prismic.KeyTextField;

  /**
   * Title field in *Feature Grid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Introduction field in *Feature Grid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.introduction
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  introduction: prismic.RichTextField;

  /**
   * Key Title field in *Feature Grid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.key_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  key_title: prismic.KeyTextField;

  /**
   * Cards field in *Feature Grid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_grid.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<FeatureGridSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for Feature Grid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeatureGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Feature Grid*
 */
type FeatureGridSliceVariation = FeatureGridSliceDefault;

/**
 * Feature Grid Shared Slice
 *
 * - **API ID**: `feature_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureGridSlice = prismic.SharedSlice<
  "feature_grid",
  FeatureGridSliceVariation
>;

/**
 * Primary content in *Featured Profile → Default → Primary*
 */
export interface FeaturedProfileSliceDefaultPrimary {
  /**
   * overlay pretitle field in *Featured Profile → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_profile.default.primary.overlay_pretitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  overlay_pretitle: prismic.KeyTextField;

  /**
   * overlay title field in *Featured Profile → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_profile.default.primary.overlay_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  overlay_title: prismic.KeyTextField;

  /**
   * overlay description field in *Featured Profile → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_profile.default.primary.overlay_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  overlay_description: prismic.KeyTextField;

  /**
   * Featured image field in *Featured Profile → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_profile.default.primary.featured_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Overlay details field in *Featured Profile → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_profile.default.primary.overlay_details
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  overlay_details: prismic.RichTextField;

  /**
   * Content field in *Featured Profile → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_profile.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Callout title field in *Featured Profile → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_profile.default.primary.callout_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  callout_title: prismic.KeyTextField;

  /**
   * Callout content field in *Featured Profile → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_profile.default.primary.callout_content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  callout_content: prismic.RichTextField;

  /**
   * Quote field in *Featured Profile → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_profile.default.primary.quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;
}

/**
 * Default variation for Featured Profile Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedProfileSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedProfileSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Featured Profile*
 */
type FeaturedProfileSliceVariation = FeaturedProfileSliceDefault;

/**
 * Featured Profile Shared Slice
 *
 * - **API ID**: `featured_profile`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedProfileSlice = prismic.SharedSlice<
  "featured_profile",
  FeaturedProfileSliceVariation
>;

/**
 * Item in *Foundation Overview → Default → Primary → Trustees*
 */
export interface FoundationOverviewSliceDefaultPrimaryTrusteesItem {
  /**
   * Trustee name field in *Foundation Overview → Default → Primary → Trustees*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foundation_overview.default.primary.trustees[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Trustee role field in *Foundation Overview → Default → Primary → Trustees*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foundation_overview.default.primary.trustees[].role
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role: prismic.KeyTextField;

  /**
   * Trustee responsibility field in *Foundation Overview → Default → Primary → Trustees*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foundation_overview.default.primary.trustees[].responsibility
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  responsibility: prismic.KeyTextField;
}

/**
 * Primary content in *Foundation Overview → Default → Primary*
 */
export interface FoundationOverviewSliceDefaultPrimary {
  /**
   * pretitle field in *Foundation Overview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foundation_overview.default.primary.pretitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  pretitle: prismic.KeyTextField;

  /**
   * title field in *Foundation Overview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foundation_overview.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * highlights title field in *Foundation Overview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foundation_overview.default.primary.highlights_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  highlights_title: prismic.KeyTextField;

  /**
   * trust pretitle field in *Foundation Overview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foundation_overview.default.primary.trust_pretitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  trust_pretitle: prismic.KeyTextField;

  /**
   * trust title field in *Foundation Overview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foundation_overview.default.primary.trust_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  trust_title: prismic.KeyTextField;

  /**
   * trust description field in *Foundation Overview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foundation_overview.default.primary.trust_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  trust_description: prismic.KeyTextField;

  /**
   * banner text field in *Foundation Overview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foundation_overview.default.primary.banner_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  banner_text: prismic.KeyTextField;

  /**
   * Mission content field in *Foundation Overview → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foundation_overview.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Trust highlights field in *Foundation Overview → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: foundation_overview.default.primary.highlights
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  highlights: prismic.RichTextField;

  /**
   * Trustees field in *Foundation Overview → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: foundation_overview.default.primary.trustees[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  trustees: prismic.GroupField<
    Simplify<FoundationOverviewSliceDefaultPrimaryTrusteesItem>
  >;

  /**
   * Actions field in *Foundation Overview → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: foundation_overview.default.primary.actions
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  actions: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "support" | "vision" | "csr"
    >
  >;

  /**
   * Volunteer action field in *Foundation Overview → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: foundation_overview.default.primary.volunteer
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  volunteer: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Foundation Overview Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FoundationOverviewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FoundationOverviewSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Foundation Overview*
 */
type FoundationOverviewSliceVariation = FoundationOverviewSliceDefault;

/**
 * Foundation Overview Shared Slice
 *
 * - **API ID**: `foundation_overview`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FoundationOverviewSlice = prismic.SharedSlice<
  "foundation_overview",
  FoundationOverviewSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Background Color field in *Hero → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.background_color
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  background_color: prismic.SelectField<"Light" | "Dark">;

  /**
   * Background Type field in *Hero → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.default.primary.background_type
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  background_type: prismic.BooleanField;

  /**
   * Pre Title Background Color field in *Hero → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.pre_title_background_color
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  pre_title_background_color: prismic.SelectField<"Light" | "Dark">;

  /**
   * Pre-title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.pre_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  pre_title: prismic.KeyTextField;

  /**
   * Content field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * CTA field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Solid Orange" | "Solid Blue" | "Solid White" | "Solid Cream"
    >
  >;

  /**
   * CTA Size field in *Hero → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero.default.primary.cta_size
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  cta_size: prismic.BooleanField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Impact Overview → Default → Primary → Repetable Item*
 */
export interface ImpactOverviewSliceDefaultPrimaryRepetableItemItem {
  /**
   * Impact Statement field in *Impact Overview → Default → Primary → Repetable Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impact_overview.default.primary.repetable_item[].impact_statement
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  impact_statement: prismic.KeyTextField;
}

/**
 * Primary content in *Impact Overview → Default → Primary*
 */
export interface ImpactOverviewSliceDefaultPrimary {
  /**
   * title field in *Impact Overview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impact_overview.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Impact Overview → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impact_overview.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Highlight Text field in *Impact Overview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impact_overview.default.primary.highlight_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  highlight_text: prismic.KeyTextField;

  /**
   * Repetable Item field in *Impact Overview → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: impact_overview.default.primary.repetable_item[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  repetable_item: prismic.GroupField<
    Simplify<ImpactOverviewSliceDefaultPrimaryRepetableItemItem>
  >;
}

/**
 * Default variation for Impact Overview Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImpactOverviewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImpactOverviewSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Impact Overview*
 */
type ImpactOverviewSliceVariation = ImpactOverviewSliceDefault;

/**
 * Impact Overview Shared Slice
 *
 * - **API ID**: `impact_overview`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImpactOverviewSlice = prismic.SharedSlice<
  "impact_overview",
  ImpactOverviewSliceVariation
>;

/**
 * Item in *Impact Stats → Default → Primary → Stats*
 */
export interface ImpactStatsSliceDefaultPrimaryStatsItem {
  /**
   * Title field in *Impact Stats → Default → Primary → Stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impact_stats.default.primary.stats[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Impact Stats → Default → Primary → Stats*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: impact_stats.default.primary.stats[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *Impact Stats → Default → Primary*
 */
export interface ImpactStatsSliceDefaultPrimary {
  /**
   * Stats field in *Impact Stats → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: impact_stats.default.primary.stats[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  stats: prismic.GroupField<Simplify<ImpactStatsSliceDefaultPrimaryStatsItem>>;
}

/**
 * Default variation for Impact Stats Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImpactStatsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImpactStatsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Impact Stats*
 */
type ImpactStatsSliceVariation = ImpactStatsSliceDefault;

/**
 * Impact Stats Shared Slice
 *
 * - **API ID**: `impact_stats`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ImpactStatsSlice = prismic.SharedSlice<
  "impact_stats",
  ImpactStatsSliceVariation
>;

/**
 * Item in *Initiative Feature → Default → Primary → Initiatives*
 */
export interface InitiativeFeatureSliceDefaultPrimaryInitiativesItem {
  /**
   * Initiative description field in *Initiative Feature → Default → Primary → Initiatives*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: initiative_feature.default.primary.initiatives[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *Initiative Feature → Default → Primary*
 */
export interface InitiativeFeatureSliceDefaultPrimary {
  /**
   * anchor id field in *Initiative Feature → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: initiative_feature.default.primary.anchor_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  anchor_id: prismic.KeyTextField;

  /**
   * pretitle field in *Initiative Feature → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: initiative_feature.default.primary.pretitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  pretitle: prismic.KeyTextField;

  /**
   * title field in *Initiative Feature → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: initiative_feature.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * image badge field in *Initiative Feature → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: initiative_feature.default.primary.image_badge
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image_badge: prismic.KeyTextField;

  /**
   * image title field in *Initiative Feature → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: initiative_feature.default.primary.image_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  image_title: prismic.KeyTextField;

  /**
   * initiatives heading field in *Initiative Feature → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: initiative_feature.default.primary.initiatives_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  initiatives_heading: prismic.KeyTextField;

  /**
   * Featured image field in *Initiative Feature → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: initiative_feature.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Description field in *Initiative Feature → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: initiative_feature.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Initiatives field in *Initiative Feature → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: initiative_feature.default.primary.initiatives[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  initiatives: prismic.GroupField<
    Simplify<InitiativeFeatureSliceDefaultPrimaryInitiativesItem>
  >;

  /**
   * Actions field in *Initiative Feature → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: initiative_feature.default.primary.actions
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  actions: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "sponsor" | "explore" | "volunteer"
    >
  >;
}

/**
 * Default variation for Initiative Feature Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InitiativeFeatureSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InitiativeFeatureSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Initiative Feature*
 */
type InitiativeFeatureSliceVariation = InitiativeFeatureSliceDefault;

/**
 * Initiative Feature Shared Slice
 *
 * - **API ID**: `initiative_feature`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InitiativeFeatureSlice = prismic.SharedSlice<
  "initiative_feature",
  InitiativeFeatureSliceVariation
>;

/**
 * Primary content in *Partnership Callout → Default → Primary*
 */
export interface PartnershipCalloutSliceDefaultPrimary {
  /**
   * pretitle field in *Partnership Callout → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partnership_callout.default.primary.pretitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  pretitle: prismic.KeyTextField;

  /**
   * title field in *Partnership Callout → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partnership_callout.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Content field in *Partnership Callout → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partnership_callout.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Actions field in *Partnership Callout → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: partnership_callout.default.primary.actions
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  actions: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "donation" | "volunteer" | "partnership"
    >
  >;
}

/**
 * Default variation for Partnership Callout Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PartnershipCalloutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PartnershipCalloutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Partnership Callout*
 */
type PartnershipCalloutSliceVariation = PartnershipCalloutSliceDefault;

/**
 * Partnership Callout Shared Slice
 *
 * - **API ID**: `partnership_callout`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PartnershipCalloutSlice = prismic.SharedSlice<
  "partnership_callout",
  PartnershipCalloutSliceVariation
>;

/**
 * Item in *Program Directory → Default → Primary → Programs*
 */
export interface ProgramDirectorySliceDefaultPrimaryProgramsItem {
  /**
   * Category field in *Program Directory → Default → Primary → Programs*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Education & Scholars
   * - **API ID Path**: program_directory.default.primary.programs[].category
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  category: prismic.SelectField<
    "Education & Scholars" | "Sanctuaries & Temples" | "Youth & Community",
    "filled"
  >;

  /**
   * Icon field in *Program Directory → Default → Primary → Programs*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: book
   * - **API ID Path**: program_directory.default.primary.programs[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<
    | "book"
    | "graduation"
    | "heart"
    | "temple"
    | "research"
    | "sparkles"
    | "community",
    "filled"
  >;

  /**
   * Program badge field in *Program Directory → Default → Primary → Programs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: program_directory.default.primary.programs[].badge
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  badge: prismic.KeyTextField;

  /**
   * Program title field in *Program Directory → Default → Primary → Programs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: program_directory.default.primary.programs[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Program description field in *Program Directory → Default → Primary → Programs*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: program_directory.default.primary.programs[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Focus areas field in *Program Directory → Default → Primary → Programs*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: program_directory.default.primary.programs[].focus_areas
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  focus_areas: prismic.RichTextField;

  /**
   * Program action field in *Program Directory → Default → Primary → Programs*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: program_directory.default.primary.programs[].action
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  action: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Program Directory → Default → Primary*
 */
export interface ProgramDirectorySliceDefaultPrimary {
  /**
   * pretitle field in *Program Directory → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: program_directory.default.primary.pretitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  pretitle: prismic.KeyTextField;

  /**
   * title field in *Program Directory → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: program_directory.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * description field in *Program Directory → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: program_directory.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Programs field in *Program Directory → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: program_directory.default.primary.programs[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  programs: prismic.GroupField<
    Simplify<ProgramDirectorySliceDefaultPrimaryProgramsItem>
  >;
}

/**
 * Default variation for Program Directory Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProgramDirectorySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProgramDirectorySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Program Directory*
 */
type ProgramDirectorySliceVariation = ProgramDirectorySliceDefault;

/**
 * Program Directory Shared Slice
 *
 * - **API ID**: `program_directory`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProgramDirectorySlice = prismic.SharedSlice<
  "program_directory",
  ProgramDirectorySliceVariation
>;

/**
 * Primary content in *Text Section → Default → Primary*
 */
export interface TextSectionSliceDefaultPrimary {
  /**
   * Heading field in *Text Section → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Content field in *Text Section → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_section.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for Text Section Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Text Section*
 */
type TextSectionSliceVariation = TextSectionSliceDefault;

/**
 * Text Section Shared Slice
 *
 * - **API ID**: `text_section`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextSectionSlice = prismic.SharedSlice<
  "text_section",
  TextSectionSliceVariation
>;

/**
 * Item in *Values Actions → Default → Primary → Values*
 */
export interface ValuesActionsSliceDefaultPrimaryValuesItem {
  /**
   * Title field in *Values Actions → Default → Primary → Values*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: values_actions.default.primary.values[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Values Actions → Default → Primary → Values*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: values_actions.default.primary.values[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *Values Actions → Default → Primary*
 */
export interface ValuesActionsSliceDefaultPrimary {
  /**
   * Heading field in *Values Actions → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: values_actions.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * Values field in *Values Actions → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: values_actions.default.primary.values[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  values: prismic.GroupField<
    Simplify<ValuesActionsSliceDefaultPrimaryValuesItem>
  >;

  /**
   * Content field in *Values Actions → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: values_actions.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Actions field in *Values Actions → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: values_actions.default.primary.actions
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  actions: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Solid Orange" | "Solid Blue" | "Solid White"
    >
  >;
}

/**
 * Default variation for Values Actions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ValuesActionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ValuesActionsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Values Actions*
 */
type ValuesActionsSliceVariation = ValuesActionsSliceDefault;

/**
 * Values Actions Shared Slice
 *
 * - **API ID**: `values_actions`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ValuesActionsSlice = prismic.SharedSlice<
  "values_actions",
  ValuesActionsSliceVariation
>;

/**
 * Item in *Vision Mission → Default → Primary → Pillars*
 */
export interface VisionMissionSliceDefaultPrimaryPillarsItem {
  /**
   * Pillar title field in *Vision Mission → Default → Primary → Pillars*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_mission.default.primary.pillars[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Pillar description field in *Vision Mission → Default → Primary → Pillars*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_mission.default.primary.pillars[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *Vision Mission → Default → Primary*
 */
export interface VisionMissionSliceDefaultPrimary {
  /**
   * Vision Pretitle field in *Vision Mission → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_mission.default.primary.vision_pretitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  vision_pretitle: prismic.KeyTextField;

  /**
   * Vision Title field in *Vision Mission → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_mission.default.primary.vision_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  vision_title: prismic.KeyTextField;

  /**
   * Vision Quote field in *Vision Mission → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_mission.default.primary.vision_quote
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  vision_quote: prismic.KeyTextField;

  /**
   * Vision Footer field in *Vision Mission → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_mission.default.primary.vision_footer
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  vision_footer: prismic.KeyTextField;

  /**
   * Mission Pretitle field in *Vision Mission → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_mission.default.primary.mission_pretitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  mission_pretitle: prismic.KeyTextField;

  /**
   * Mission Title field in *Vision Mission → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_mission.default.primary.mission_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  mission_title: prismic.KeyTextField;

  /**
   * Mission Description field in *Vision Mission → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_mission.default.primary.mission_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  mission_description: prismic.KeyTextField;

  /**
   * Pillars field in *Vision Mission → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: vision_mission.default.primary.pillars[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  pillars: prismic.GroupField<
    Simplify<VisionMissionSliceDefaultPrimaryPillarsItem>
  >;
}

/**
 * Default variation for Vision Mission Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VisionMissionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VisionMissionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Vision Mission*
 */
type VisionMissionSliceVariation = VisionMissionSliceDefault;

/**
 * Vision Mission Shared Slice
 *
 * - **API ID**: `vision_mission`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VisionMissionSlice = prismic.SharedSlice<
  "vision_mission",
  VisionMissionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContactInquirySlice,
      ContactInquirySliceDefaultPrimaryContactDetailsItem,
      ContactInquirySliceDefaultPrimary,
      ContactInquirySliceVariation,
      ContactInquirySliceDefault,
      CtaBannerSlice,
      CtaBannerSliceDefaultPrimary,
      CtaBannerSliceVariation,
      CtaBannerSliceDefault,
      FeatureGridSlice,
      FeatureGridSliceDefaultPrimaryCardsItem,
      FeatureGridSliceDefaultPrimary,
      FeatureGridSliceVariation,
      FeatureGridSliceDefault,
      FeaturedProfileSlice,
      FeaturedProfileSliceDefaultPrimary,
      FeaturedProfileSliceVariation,
      FeaturedProfileSliceDefault,
      FoundationOverviewSlice,
      FoundationOverviewSliceDefaultPrimaryTrusteesItem,
      FoundationOverviewSliceDefaultPrimary,
      FoundationOverviewSliceVariation,
      FoundationOverviewSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ImpactOverviewSlice,
      ImpactOverviewSliceDefaultPrimaryRepetableItemItem,
      ImpactOverviewSliceDefaultPrimary,
      ImpactOverviewSliceVariation,
      ImpactOverviewSliceDefault,
      ImpactStatsSlice,
      ImpactStatsSliceDefaultPrimaryStatsItem,
      ImpactStatsSliceDefaultPrimary,
      ImpactStatsSliceVariation,
      ImpactStatsSliceDefault,
      InitiativeFeatureSlice,
      InitiativeFeatureSliceDefaultPrimaryInitiativesItem,
      InitiativeFeatureSliceDefaultPrimary,
      InitiativeFeatureSliceVariation,
      InitiativeFeatureSliceDefault,
      PartnershipCalloutSlice,
      PartnershipCalloutSliceDefaultPrimary,
      PartnershipCalloutSliceVariation,
      PartnershipCalloutSliceDefault,
      ProgramDirectorySlice,
      ProgramDirectorySliceDefaultPrimaryProgramsItem,
      ProgramDirectorySliceDefaultPrimary,
      ProgramDirectorySliceVariation,
      ProgramDirectorySliceDefault,
      TextSectionSlice,
      TextSectionSliceDefaultPrimary,
      TextSectionSliceVariation,
      TextSectionSliceDefault,
      ValuesActionsSlice,
      ValuesActionsSliceDefaultPrimaryValuesItem,
      ValuesActionsSliceDefaultPrimary,
      ValuesActionsSliceVariation,
      ValuesActionsSliceDefault,
      VisionMissionSlice,
      VisionMissionSliceDefaultPrimaryPillarsItem,
      VisionMissionSliceDefaultPrimary,
      VisionMissionSliceVariation,
      VisionMissionSliceDefault,
    };
  }
}
