export const modalContent = {
  modal_title: "Support sacred seva",
  modal_subtitle: "Donate to Shree Raja Mathangi Foundation",
  modal_description: "Every contribution preserves ancient Vedas, cares for sacred Desi cows, and restores historic temples.",
  modal_seva_title: "Select seva cause",
  modal_seva: [
    { seva_id: "go-samrakshnam", title: "Go Samrakshnam", subtitle: "Fodder & Cow Care" },
    { seva_id: "vedic-education", title: "Vedic Education", subtitle: "Gurukul & Scholars" },
    { seva_id: "temple-management", title: "Temple Management", subtitle: "Pooja & Renovation" },
  ],
  modal_donation_amount_title: "Select donation amount (₹)",
  modal_amounts: [501, 1100, 2100, 5100].map(amount => ({ amount })),
  modal_enter_amount_label: "Enter custom amount",
  modal_donor_information_title: "Donor information",
  modal_full_name_label: "Full name *",
  modal_email_label: "Email address *",
  modal_phone_label: "Phone number *",
  modal_pan_label: "PAN number (optional)",
  modal_info_title: "How your seva transforms lives",
  modal_info: ["Educates future Vedic scholars", "Protects & feeds indigenous cows", "Preserves sacred temples & traditions", "Supports teachers, students & seva", "Promotes heritage research & archives", "Builds sustainable preservation infrastructure"].map(text => ({ type: "list-item", text, spans: [] })),
  modal_highlight_text: "Submit a pledge and our team will contact you about payment and receipt arrangements. PAN is optional and used only for receipt processing.",
  modal_submit_text: "Submit seva pledge",
  modal_submitting_text: "Saving your pledge…",
  modal_success_title: "Thank you for your seva pledge",
  modal_success_description: "Our team will contact you to arrange your contribution. No payment has been collected.",
  modal_done_label: "Done",
  modal_close_label: "Close donation form",
};
