// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  contact_inquiry: dynamic(() => import("./ContactInquiry")),
  feature_grid: dynamic(() => import("./FeatureGrid")),
  featured_profile: dynamic(() => import("./FeaturedProfile")),
  foundation_overview: dynamic(() => import("./FoundationOverview")),
  hero: dynamic(() => import("./Hero")),
  impact_overview: dynamic(() => import("./ImpactOverview")),
  initiative_feature: dynamic(() => import("./InitiativeFeature")),
  pillar_feature: dynamic(() => import("./PillarFeature")),
  vision_mission: dynamic(() => import("./VisionMission")),
};
