// Code generated by Prismic. DO NOT EDIT.

import ContactInquiry from "./ContactInquiry";
import FeatureGrid from "./FeatureGrid";
import FeaturedProfile from "./FeaturedProfile";
import FoundationOverview from "./FoundationOverview";
import Hero from "./Hero";
import ImpactOverview from "./ImpactOverview";
import InitiativeFeature from "./InitiativeFeature";
import PillarFeature from "./PillarFeature";
import TrustMembers from "./TrustMembers";
import VisionMission from "./VisionMission";

export const components = {
	contact_inquiry: ContactInquiry,
	feature_grid: FeatureGrid,
	featured_profile: FeaturedProfile,
	foundation_overview: FoundationOverview,
	hero: Hero,
	impact_overview: ImpactOverview,
	initiative_feature: InitiativeFeature,
	pillar_feature: PillarFeature,
	trust_members: TrustMembers,
	vision_mission: VisionMission
};